=== openhwgroup/uap/cfg/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Virtual Repository IP list (array of entries)",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["Name", "Category"],
    "properties": {
      "Name": { "type": "string", "minLength": 1 },
      "Category": {
        "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "URL": { "type": "string", "format": "uri" },
      "IP_CARD_URL":{"type":"string","format":"uri"},
      "Project": { "type": "string" },
      "WI": {
        "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "Partners": {
        "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "Status": { "type": "string" },
      "Description": { "type": "string" },
      "License": {
         "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "Comment": { "type": "string" }
    },
    "additionalProperties": true
  }
}

=== openhwgroup/uap/ips/rebecca.json
[
  {
    "Name": "RISC-V Main Processor Complex",
    "Category" : ["Hardware", "RISC-V Processing System"],
    "IP_CARD_URL": "",
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "Open-Source",
    "Status": "Work in progress",
    "Description": "A four-core CVA6 ISA RISC-V implementation",
    "License": "Others",
    "Comment": "Open-Source. TBD"
  },
  {
    "Name": "AXI Crossbar for Central Interconnect",
    "Category" : ["Hardware", "RISC-V Processing System"],
    "IP_CARD_URL": "",
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "EXA",
    "Status": "",
    "Description": "A crossbar that allows for the interfacing between the RISC-V processor and various peripherals inside the chiplet",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "Intrusion-Detection System (IDS) Module",
    "Category" : ["Hardware", "Accelerators on ASIC"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "TUC",
    "Status": "",
    "Description": "It implemenets the Aho-Corasick pattern matching algorithm for detection of malicious activity on the chip",
    "License": "GPL",
    "Comment": "TBD"
  },
  {
    "Name": "Neuromorphic Accelerator",
    "Category" : ["Hardware", "Accelerators on ASIC"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "IMEC",
    "Status": "",
    "Description": "AI accelerator inside the REBECCA chiplet that brings exploits neuromorphic architectures offering scalability and energy efficiency.",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "Near-memory Processing (NMP) Accelerator",
    "Category" : ["Hardware", "Accelerators on ASIC"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "LUND",
    "Status": "",
    "Description": "Co-processor inside the REBECCA chiplet",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "Watchdog AI Accelerator",
    "Category" : ["Hardware", "Accelerators on Reconfigurable Logic"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "SYN",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "FORTH AI Accelerator",
    "Category" : ["Hardware", "Accelerators on Reconfigurable Logic"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "FORTH",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "ML Accelerator",
    "Category" : ["Hardware", "Accelerators on Reconfigurable Logic"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "CSEM",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "CNN Accelerator",
    "Category" : ["Hardware", "Accelerators on Reconfigurable Logic"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "POLITO",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "Chip2FPGA",
    "Category" : "Hardware",
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "EXA",
    "Status": "",
    "Description": "Chip2FPGA Controller",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "Chip2Chip Interface",
    "Category" : "Hardware",
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "FRAUN",
    "Status": "",
    "Description": "Chiplet Interconnection",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "I/O Coherency",
    "Category" : "Hardware",
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "Open-Source",
    "Status": "",
    "Description": "Coherent data for ASIC accelerators accessing L2 cache",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "DMA",
    "Category" : "Hardware",
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "EXA",
    "Status": "",
    "Description": "Fast data transfer support between RISC-V subsystem and external memories",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "Booting Devices",
    "Category" : "Hardware",
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "EXA",
    "Status": "",
    "Description": "Support for BootROM as well as BootRAM for SD and/or JTAG boot",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "PikeOS and Hypervisor",
    "Category" : ["Software", "System Software"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "SYSGO",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "XtratuM Hypervisor",
    "Category" : ["Software", "System Software"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "FENTISS",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD",
    "IP_CARD_URL": "https://github.com/pulp-unibo/ip-card/blob/main/examples/FENTISS_xng.json"
  },
  {
    "Name": "Kubernetes",
    "Category" : ["Software", "Middleware and Orchestration"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "FORTH",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "SafeLayer",
    "Category" : ["Software", "Middleware and Orchestration"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "ZHAW",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "ROS2",
    "Category" : ["Software", "Middleware and Orchestration"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "ALM",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "Asimovo",
    "Category" : ["Software", "Middleware and Orchestration"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "ALM",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "RISC-V Software AI Inference Engine",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "Klepsydra",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "FPGA Software AI Inference Engine",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "Klepsydra",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "LPDNN",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "Klepsydra",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "AI Asset Workflow",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "BCA",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "DNN Safety Layer",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "BSC",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "EDDL Library",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "SML",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "YOLO-based Object Detector and Image Processing Algorithm",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "ARCELIK",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "SDK for Neuromorphic Accelerator",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "IMEC",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "SDK for Watchdog AI Accelerator",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "SYN",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "ML Compiler for ML Accelerator",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "CSEM",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "ML Design Space Exploration and Compiler for CNN Accelerator",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "POLITO",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "AI Mapper",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "ZHAW",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  },
  {
    "Name": "Asimovo-based AI Algorithms",
    "Category" : ["Software", "AI Frameworks"],
    "URL": "",
    "Project": "REBECCA",
    "WI": [""],
    "Partners": "ALM",
    "Status": "",
    "Description": "",
    "License": "Others",
    "Comment": "TBD"
  }
]
